baseURL = "https://blog.penguincabinet.com/"
title = "愛を感じるペンギン内閣"
theme = "hugo-geekblog"

pluralizeListTitles = false

# Geekblog required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
hasCJKLanguage = true
summaryLength = 140

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  author = "PenguinCabinet"
  tag = "tags"
  category = "categories"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.Atom]
    name = "Atom"
    mediaType = "application/atom+xml"
    baseName = "feed"
    isPlainText = false
    rel = "alternate"
    isHTML = false
    noUgly = true
    permalinkable = false

[outputs]
  home = ["HTML", "ATOM"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML", "ATOM"]

[params]
  twitterCardEnabled = true
  # twitterCardSite = 
  twitterCardDomain = "https://blog.penguincabinet.com/"
  twitterCardAuthor = "PenguinCabinet"
  images=["favicon/favicon.png"]